Updates MDL controls to allow remote updates. Closes #65.
material-foundation/material-remixer-web pull request #66
Opened 2017-01-17 17:35 UTC by chriscox

2017-01-17 19:50 UTC, appsforartists requested changes

2017-01-17 19:50 UTC, appsforartists commented on src/ui/controls/RadioListControl.tsx
>    /** @override */
Are the `@override`s necessary?  React components are expected to implement these methods.

2017-01-17 19:50 UTC, appsforartists commented on src/ui/controls/RadioListControl.tsx
> +
The `this.refs[key]` syntax is deprecated:

https://facebook.github.io/react/docs/refs-and-the-dom.html

Please use the callback syntax instead.

2017-01-17 19:57 UTC, chriscox commented on src/ui/controls/RadioListControl.tsx
>    /** @override */
I've added these only for future-proofing compatibility with closure compiler per recommendation here: http://usejsdoc.org/tags-override.html

2017-01-17 21:18 UTC, chriscox commented on src/ui/controls/RadioListControl.tsx
> +
Done. PTAL.

2017-01-17 21:18 UTC, chriscox reviewed
Updated the refs to use callbacks.

2017-01-17 22:16 UTC, appsforartists commented on src/ui/controls/SwitchControl.tsx
> +    let materialSwitch = this.switchControl["MaterialRadio"];
Where is MaterialRadio coming from?  Isn't this a DOM element?

2017-01-17 22:18 UTC, chriscox commented on src/ui/controls/SwitchControl.tsx
> +    let materialSwitch = this.switchControl["MaterialRadio"];
Sorry I had previously fixed that misspelling.  Its changed to MaterialSwitch (not sure why its showing the old one here.

2017-01-17 22:19 UTC, chriscox commented on src/ui/controls/SwitchControl.tsx
> +    let materialSwitch = this.switchControl["MaterialRadio"];
And yes, MDL attaches these data elements to the controls, and each one has a specific way to trigger events programmatically on it.

2017-01-17 22:44 UTC, appsforartists commented on src/ui/controls/RadioListControl.tsx
>    /** @override */
But it's not overriding anything:

https://github.com/facebook/react/blob/c78464f8ea9a5b00ec80252d20a71a1482210e57/src/isomorphic/modern/class/ReactComponent.js

https://github.com/facebook/react/blob/3bc5595dfd6db741b19f17e7aef98b2c1e4be847/src/renderers/shared/stack/reconciler/ReactCompositeComponent.js#L331

2017-01-17 22:55 UTC, appsforartists commented
Are there docs somewhere for MaterialRadio?  I can't find it.

2017-01-17 22:59 UTC, chriscox commented on src/ui/controls/RadioListControl.tsx
>    /** @override */
Done.  Interesting... thanks for pointing that out. Updated. And I'll create separate PR to flush out the unnecessary overrides in other the classes.

2017-01-17 23:02 UTC, chriscox commented
Unfortunately the docs are somewhat limited. However I'm following the recommended technique.. which you can find documented in the slider readme as an example:
https://github.com/google/material-design-lite/tree/mdl-1.x/src/slider#configuration-options

2017-01-18 00:25 UTC, appsforartists approved these changes

2017-01-18 11:59 UTC, merged